----1. Create database ----DATA_ENGINEERING_P1
----2. Create a schema-----DBO
----3. LOAD THE TABLES-----CUSTOMERS, PRODUCTS AND ORDERS

SELECT *
    FROM DATA_ENGINEERING_P1.DBO.CUSTOMERS

Select *
From DATA_ENGINEERING_P1.DBO.ORDERS

Select *
From DATA_ENGINEERING_P1.DBO.PRODUCTS
---JOINING TABLES
SELECT
    A.CUSTOMER_ID,
    A.CUSTOMER_NAME,
    B.ORDER_ID,
    B.PRODUCT_ID,
    C.CATEGORY,
    C.PRODUCT_NAME,
    C.UNIT_PRICE * B.QUANTITY Revenue
FROM DATA_ENGINEERING_P1.DBO.CUSTOMERS AS A
JOIN DATA_ENGINEERING_P1.DBO.ORDERS AS B
    ON A.CUSTOMER_ID = B.CUSTOMER_ID
JOIN DATA_ENGINEERING_P1.DBO.PRODUCTS AS C
    ON B.PRODUCT_ID = C.PRODUCT_ID;
---TOTAL REVENUE PER CUSTOMER
Select 
A.Customer_ID,
A.CUSTOMER_Name,
SUM(B.QUANTITY * C.UNIT_PRICE) AS TOTAL_REVENUE
FROM DATA_ENGINEERING_P1.DBO.CUSTOMERS AS A
JOIN DATA_ENGINEERING_P1.DBO.ORDERS AS B
    ON A.CUSTOMER_ID = B.CUSTOMER_ID
JOIN DATA_ENGINEERING_P1.DBO.PRODUCTS AS C
    ON B.PRODUCT_ID = C.PRODUCT_ID
 GROUP BY
    A.CUSTOMER_ID,
    A.CUSTOMER_NAME;
  ----Total Revenue Per Product
  SELECT 
    C.CATEGORY,
    SUM(B.QUANTITY * C.UNIT_PRICE) AS PRODUCT_REVENUE
FROM DATA_ENGINEERING_P1.DBO.CUSTOMERS AS A
JOIN DATA_ENGINEERING_P1.DBO.ORDERS AS B
    ON A.CUSTOMER_ID = B.CUSTOMER_ID
JOIN DATA_ENGINEERING_P1.DBO.PRODUCTS AS C
    ON B.PRODUCT_ID = C.PRODUCT_ID
GROUP BY
    C.CATEGORY;
----TOP 5 CUSTOMERS
Select 
A.CUSTOMER_ID,
A.CUSTOMER_NAME,
B.QUANTITY * C.UNIT_PRICE AS TOTAL_SPEND
FROM DATA_ENGINEERING_P1.DBO.CUSTOMERS AS A
JOIN DATA_ENGINEERING_P1.DBO.ORDERS AS B
    ON A.CUSTOMER_ID = B.CUSTOMER_ID
JOIN DATA_ENGINEERING_P1.DBO.PRODUCTS AS C
    ON B.PRODUCT_ID = C.PRODUCT_ID
    LIMIT 5;